### ISSUE TITLE
Add a mmol/L option for displaying results

### ISSUE THREAD

**Issue by Hangar85** [Crazy-Marvin/LibreLinkUpDesktop#281]
### :warning: Is your feature request related to a problem? Please describe.
Data is only displaying in mg/dL

### :bulb: Describe the solution you'd like.
Data available in mmol/L for UK users

### :bar_chart: Describe alternatives you've considered.
NA

### :page_facing_up: Additional context
NA

### :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ X ] No

I'm afraid I'm not a coder so wouldn't really know how to implement this feature.

In the UK values are shown as mmol/L rather than mg/dL
https://www.diabetes.co.uk/blood-sugar-converter.html

Would it be possible to have an option in the settings section to be able to toggle this?

**Comment by CrazyMarvin** [comment]
Do you see the correct values but just the measuring unit is wrong?
May you share a screenshot please?

**Comment by Hangar85** [comment]
Of course
I believe the values are correct, it's just we don't use the mg/dL values in the UK.

<img width="212" alt="image" src="https://github.com/Crazy-Marvin/LibreLinkUpDesktop/assets/69671080/65a0c6e3-eb0d-42f4-9533-e53edb5945ff">

Screenshot from the LibreLinkUp app :
<img width="158" alt="image" src="https://github.com/Crazy-Marvin/LibreLinkUpDesktop/assets/69671080/ea087f12-5654-4d8d-a00c-e65648740eec">

**Comment by Kev1nr1** [comment]
> Do you see the correct values but just the measuring unit is wrong? May you share a screenshot please?

This should (hopefully haha) be easily solvable. If it would be possible in the settings menu to add another option called display setting or something where you can select mg/dl or mmol/l, the only thing that needs to be changed in the back-end would be to display it instead of 146mg/dl -> (146*0.0555)=8.2 mmol/l

**Comment by byBlurr** [comment]
Here is how we convert between mmol/L and mg/dl:

mmol/L = (mg/dl / 18)
mg/dl = (mmol/L * 18)

**Comment by tebz** [comment]
mmol/L is also used in Sweden

**Comment by CrazyMarvin** [comment]
We hope to implement the unit next month.

**Comment by frigaut** [comment]
That'd be great. We also use mmol/l in Australia.

**Comment by TomasAbeck** [comment]
Thanks for mmol/L support. Can you please add one decimal place? 
![Example librelink](https://github.com/user-attachments/assets/4649dbb3-a735-4f5f-92b5-eb7610380dca)

I created a Czech translation as a thank you.

**Comment by CrazyMarvin** [comment]
> Thanks for mmol/L support. Can you please add one decimal place? ![Example librelink](https://private-user-images.githubusercontent.com/181109199/366056268-4649dbb3-a735-4f5f-92b5-eb7610380dca.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5Nzk1NjMsIm5iZiI6MTcyNTk3OTI2MywicGF0aCI6Ii8xODExMDkxOTkvMzY2MDU2MjY4LTQ2NDlkYmIzLWE3MzUtNGY1Zi05MmI1LWViNzYxMDM4MGRjYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDJhZGI3ZGJlMGY0ODBhOGMyZGE4YjIyZWUwYzgwNDgyOTM1Mzc3ZjJmZWRlNGUzMDY4YWNhZjY4MzMzZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gu9HDXZdVyNXwaRVKpHSy6bQQn7AbiRLrfOWmnTQ2fU)
> 
> I created a Czech translation as a thank you.

The next release should have one decimal.
Thanks for your translation.

**Comment by TomasAbeck** [comment]
Thank you, perfect!

**Comment by CrazyMarvin** [comment]
[`v0.1.11`](https://github.com/Crazy-Marvin/LibreLinkUpDesktop/releases/tag/v0.1.11) shows one decimal now.
