### ISSUE TITLE
Technology Discussion: Electron, Flutter or something else?

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/LibreLinkUpDesktop#29]
Which technology fits the LibreLinkUpDesktop best?

Target platform: Windows & Ubuntu
Nice to have but not necessary: Wear OS, Web, Android, macOS & iOS

Pro Flutter:
- It seems to be the future for rather simple mobile and desktop applications (_one language to rule them all_)

Contra Flutter:
- Not really mature

Pro Electron:
- JavaScript is around for a long time and very established 

Contra Electron:
- Many people say that JavaScript should not be used anymore (e.g. [Douglas Crockford](https://youtu.be/99Zacm7SsWQ))

**Comment by iMonZ** [comment]
Flutter has an awful UI and is also not very great to use. The UI looks outdated and there are many other one code Frameworks that look and fell much better.

I think Flutter is a thing of the past it was a great thing a few years ago but with so much better alternatives it just looks like a http website from 2003 in compared to.

I can recommend Electron or even better use MAUI from Microsoft.
Both are working with every platform!
Doesn't matter if you use Ubuntu or macOS MAUI is wonderful

**Comment by iMonZ** [comment]
https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui
https://dotnet.microsoft.com/en-us/apps/maui

**Comment by CrazyMarvin** [comment]
Thanks for your input, @iMonZ.
We will go on with Electron.

**Comment by CrazyMarvin** [comment]
Initial Release using [Electron](https://www.electronjs.org/) is available now: [https://github.com/Crazy-Marvin/LibreLinkUpDesktop/releases/tag/v0.1.2](https://github.com/Crazy-Marvin/LibreLinkUpDesktop/releases/tag/v0.1.2). 🥳

**Comment by iMonZ** [comment]
> Initial Release using [Electron](https://www.electronjs.org/) is available now: https://github.com/Crazy-Marvin/LibreLinkUpDesktop/releases/tag/v0.1.2. 🥳

Thanks.
JavaScript has its own problem but at least you are not using flutter
