### ISSUE TITLE
Adding alwaysOnTop, removing the frame and making the window draggable

### ISSUE THREAD

**Issue by rizvanaga** [Crazy-Marvin/LibreLinkUpDesktop#332]
### :bulb: Describe the solution you'd like.
I wanted to be able to see my blood sugar levels when I'm in a game/doing some intensive work on my PC and it requires my full focus while my phone was charging away from me.

### :bar_chart: Describe alternatives you've considered.
I had already started my own project using Electron and upon searching for the LibreLinkUp API I stumbled upon this magnificent thing so I chose to change the code a bit so the app can be used as an overlay (useful when playing long matches in games like CS2 etc.). 

### :page_facing_up: Additional context
I am not capable of modifying the code a bit more since I am not a code writer. I am not sure that I'll be able to upload the fork succesfully.

### :raising_hand: Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by CrazyMarvin** [comment]
Thanks for your feedback.

I am not sure if this will work. What do you think, @fperera123?

**Comment by rizvanaga** [comment]
Closed due to the features being written, awaiting approval as of today.
