### ISSUE TITLE
The mmol/L display is only integer

### ISSUE THREAD

**Issue by tebz** [Crazy-Marvin/LibreLinkUpDesktop#337]
The mmol/L display is only integer.
It's to corose.
It would be better with one decimal 

Like src\renderer\lib 49: 
return Math.round(value / 1.80182)/10

Will that change the the output also ?
I'm not a JavaScript/TypeScript programmer.

**Comment by CrazyMarvin** [comment]
[`v0.1.11`](https://github.com/Crazy-Marvin/LibreLinkUpDesktop/releases/tag/v0.1.11) shows one decimal now.
